test = {   'name': 'BatchNorm Layer',
    'points': 15,
    'suites': [   {   'cases': [   {'code': '>>> list(BatchNorm2d(2)(torch.zeros((3,2,7,6))).shape) == [3,2,7,6]\nTrue', 'hidden': False, 'locked': False, 'points': 0},
                                   {'code': '>>> type(BatchNorm2d(2)(torch.zeros((3,2,7,6)))) == torch.Tensor\nTrue', 'hidden': False, 'locked': False, 'points': 0},
                                   {'code': ">>> hasattr(BatchNorm2d(2), 'gamma') and hasattr(BatchNorm2d(2), 'beta')\nTrue", 'hidden': False, 'locked': False, 'points': 0},
                                   {   'code': '>>> layer = BatchNorm2d(7)\n>>> (list(layer.gamma.shape) == [7])  and (list(layer.beta.shape) == [7])\nTrue',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
