test = {   'name': 'Linear Layer',
    'points': 5,
    'suites': [   {   'cases': [   {'code': '>>> list(Linear(25,28)(torch.zeros((17,25))).shape) == [17,28]\nTrue', 'hidden': False, 'locked': False, 'points': 0},
                                   {'code': '>>> type(Linear(13,15)(torch.zeros((6,13)))) in [torch.Tensor, torch.nn.Parameter]\nTrue', 'hidden': False, 'locked': False, 'points': 0},
                                   {'code': ">>> hasattr(Linear(2,2), 'w') and hasattr(Linear(2,2), 'b')\nTrue", 'hidden': False, 'locked': False, 'points': 0},
                                   {   'code': '>>> layer = Linear(13,24)\n>>> (list(layer.w.shape) in [[13,24], [24,13]])  and (list(layer.b.shape) == [24])\nTrue',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
